In [2]:
import pandas as pd

In [50]:
data = pd.read_csv("otu.csv", dtype = "unicode")
data.head()

Sample1  Sample2 Sample3 Sample4  Sample5 Sample6 Sample7 Sample8 Sample9  \
0     left     left    left    left     left    left    left    left    left   
1  0.33364  0.62579       0       0  0.56233       0       0       0       0   
2  0.33364  0.62579       0       0  0.56233       0       0       0       0   
3  0.33364  0.62579       0       0  0.56233       0       0       0       0   
4  0.33364  0.62579       0       0  0.56233       0       0       0       0   

  Sample10  ... Sample262 Sample263 Sample264 Sample265 Sample266 Sample267  \
0     left  ...     right     right     right     right     right     right   
1        0  ...         0   6.11234         0         0         0         0   
2        0  ...         0   6.11234         0         0         0         0   
3        0  ...         0   6.10627         0         0         0         0   
4        0  ...         0   6.10627         0         0         0         0   

  Sample268 Sample269 Sample270 Sample271  
0     right     right     right     right  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 271 columns]

In [51]:
dataset = dataset.T
dataset.head()

0        1        2        3        4        5        6        7     \
Sample1    0  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364   
Sample2    0  0.62579  0.62579  0.62579  0.62579  0.62579  0.62579  0.49776   
Sample3    0        0        0        0        0        0        0        0   
Sample4    0        0        0        0        0        0        0        0   
Sample5    0  0.56233  0.56233  0.56233  0.56233  0.56233  0.56233  0.49446   

            8        9     ... 3293 3294 3295 3296 3297 3298 3299 3300 3301  \
Sample1  0.33364        0  ...    0    0    0    0    0    0    0    0    0   
Sample2  0.49776  0.12802  ...    0    0    0    0    0    0    0    0    0   
Sample3        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample4        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample5  0.49446  0.06786  ...    0    0    0    0    0    0    0    0    0   

        3302  
Sample1    0  
Sample2    0  
Sample3    0  
Sample4    0  
Sample5    0  

[5 rows x 3303 columns]

In [52]:
dataset

0        1        2        3        4        5        6        7     \
Sample1      0  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364   
Sample2      0  0.62579  0.62579  0.62579  0.62579  0.62579  0.62579  0.49776   
Sample3      0        0        0        0        0        0        0        0   
Sample4      0        0        0        0        0        0        0        0   
Sample5      0  0.56233  0.56233  0.56233  0.56233  0.56233  0.56233  0.49446   
...        ...      ...      ...      ...      ...      ...      ...      ...   
Sample267    1        0        0        0        0        0        0        0   
Sample268    1        0        0        0        0        0        0        0   
Sample269    1        0        0        0        0        0        0        0   
Sample270    1        0        0        0        0        0        0        0   
Sample271    1        0        0        0        0        0        0        0   

              8        9     ... 3293 3294 3295 3296 3297 3298 3299 3300 3301  \
Sample1    0.33364        0  ...    0    0    0    0    0    0    0    0    0   
Sample2    0.49776  0.12802  ...    0    0    0    0    0    0    0    0    0   
Sample3          0        0  ...    0    0    0    0    0    0    0    0    0   
Sample4          0        0  ...    0    0    0    0    0    0    0    0    0   
Sample5    0.49446  0.06786  ...    0    0    0    0    0    0    0    0    0   
...            ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
Sample267        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample268        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample269        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample270        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample271        0        0  ...    0    0    0    0    0    0    0    0    0   

          3302  
Sample1      0  
Sample2      0  
Sample3      0  
Sample4      0  
Sample5      0  
...        ...  
Sample267    0  
Sample268    0  
Sample269    0  
Sample270    0  
Sample271    0  

[271 rows x 3303 columns]

In [53]:
#turning lefts and rights into 0s and 1s
for i in range(len(dataset)):
    if dataset[0][i] == 'left':
        dataset[0][i] = 0
    elif dataset[0][i] == 'right':
        dataset[0][i] = 1
    

In [61]:
import numpy as np
X = np.array(dataset.drop(0, axis=1),dtype=float)


In [60]:
y = np.array(dataset[0], dtype=float)


In [48]:
import sys
!{sys.executable} -m pip install xgboost
import xgboost as xgb

In [65]:
data_dmatrix = xgb.DMatrix(data=X, label=y)

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [67]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [68]:
xg_reg.fit(X_train,y_train)

[02:14:24] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.3,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.1, max_bin=256,
             max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
             max_depth=5, max_leaves=0, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:linear', ...)

In [71]:
preds = xg_reg.predict(X_test)

In [178]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, preds)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [81]:
y_test

array([0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 0.])

In [83]:
preds

array([0.4226383 , 0.5287249 , 0.62475824, 0.46778283, 0.57531136,
       0.5914449 , 0.6015379 , 0.60030824, 0.5454684 , 0.3513229 ,
       0.53480196, 0.5639127 , 0.38923404, 0.55167747, 0.5708514 ,
       0.38116673, 0.55295944, 0.572083  , 0.5335631 , 0.5281434 ,
       0.40557352, 0.4311264 , 0.5042844 , 0.58537716, 0.58555406,
       0.47266683, 0.47535914, 0.43869367, 0.4850141 , 0.55029505,
       0.5927774 , 0.5909118 , 0.57797366, 0.4567047 , 0.56997484,
       0.33642334, 0.4584894 , 0.45294636, 0.5354455 , 0.3949074 ,
       0.49297452, 0.45218328, 0.53484803, 0.482896  , 0.6142305 ,
       0.5410547 , 0.5223429 , 0.5365773 , 0.49118984, 0.32706118,
       0.4612354 , 0.36826196, 0.37634313, 0.5417167 , 0.42917398],
      dtype=float32)

In [176]:
from sklearn.ensemble import AdaBoostClassifier
ada_boost = AdaBoostClassifier(n_estimators=95, learning_rate=0.8, random_state=42)
model = ada_boost.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [155]:
y_pred

array([0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0.])

In [156]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[17,  7],
       [13, 18]])

In [177]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.6545454545454545