In [7]:
import pandas as pd

In [8]:
data = pd.read_csv("otu.csv", dtype = "unicode")
data.head()

Sample1  Sample2 Sample3 Sample4  Sample5 Sample6 Sample7 Sample8 Sample9  \
0     left     left    left    left     left    left    left    left    left   
1  0.33364  0.62579       0       0  0.56233       0       0       0       0   
2  0.33364  0.62579       0       0  0.56233       0       0       0       0   
3  0.33364  0.62579       0       0  0.56233       0       0       0       0   
4  0.33364  0.62579       0       0  0.56233       0       0       0       0   

  Sample10  ... Sample262 Sample263 Sample264 Sample265 Sample266 Sample267  \
0     left  ...     right     right     right     right     right     right   
1        0  ...         0   6.11234         0         0         0         0   
2        0  ...         0   6.11234         0         0         0         0   
3        0  ...         0   6.10627         0         0         0         0   
4        0  ...         0   6.10627         0         0         0         0   

  Sample268 Sample269 Sample270 Sample271  
0     right     right     right     right  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 271 columns]

In [13]:
dataset = data.T
dataset.head()

0        1        2        3        4        5        6        7     \
Sample1  left  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364   
Sample2  left  0.62579  0.62579  0.62579  0.62579  0.62579  0.62579  0.49776   
Sample3  left        0        0        0        0        0        0        0   
Sample4  left        0        0        0        0        0        0        0   
Sample5  left  0.56233  0.56233  0.56233  0.56233  0.56233  0.56233  0.49446   

            8        9     ... 3293 3294 3295 3296 3297 3298 3299 3300 3301  \
Sample1  0.33364        0  ...    0    0    0    0    0    0    0    0    0   
Sample2  0.49776  0.12802  ...    0    0    0    0    0    0    0    0    0   
Sample3        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample4        0        0  ...    0    0    0    0    0    0    0    0    0   
Sample5  0.49446  0.06786  ...    0    0    0    0    0    0    0    0    0   

        3302  
Sample1    0  
Sample2    0  
Sample3    0  
Sample4    0  
Sample5    0  

[5 rows x 3303 columns]

In [14]:
dataset

0        1        2        3        4        5        6     \
Sample1     left  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364   
Sample2     left  0.62579  0.62579  0.62579  0.62579  0.62579  0.62579   
Sample3     left        0        0        0        0        0        0   
Sample4     left        0        0        0        0        0        0   
Sample5     left  0.56233  0.56233  0.56233  0.56233  0.56233  0.56233   
...          ...      ...      ...      ...      ...      ...      ...   
Sample267  right        0        0        0        0        0        0   
Sample268  right        0        0        0        0        0        0   
Sample269  right        0        0        0        0        0        0   
Sample270  right        0        0        0        0        0        0   
Sample271  right        0        0        0        0        0        0   

              7        8        9     ... 3293 3294 3295 3296 3297 3298 3299  \
Sample1    0.33364  0.33364        0  ...    0    0    0    0    0    0    0   
Sample2    0.49776  0.49776  0.12802  ...    0    0    0    0    0    0    0   
Sample3          0        0        0  ...    0    0    0    0    0    0    0   
Sample4          0        0        0  ...    0    0    0    0    0    0    0   
Sample5    0.49446  0.49446  0.06786  ...    0    0    0    0    0    0    0   
...            ...      ...      ...  ...  ...  ...  ...  ...  ...  ...  ...   
Sample267        0        0        0  ...    0    0    0    0    0    0    0   
Sample268        0        0        0  ...    0    0    0    0    0    0    0   
Sample269        0        0        0  ...    0    0    0    0    0    0    0   
Sample270        0        0        0  ...    0    0    0    0    0    0    0   
Sample271        0        0        0  ...    0    0    0    0    0    0    0   

          3300 3301 3302  
Sample1      0    0    0  
Sample2      0    0    0  
Sample3      0    0    0  
Sample4      0    0    0  
Sample5      0    0    0  
...        ...  ...  ...  
Sample267    0    0    0  
Sample268    0    0    0  
Sample269    0    0    0  
Sample270    0    0    0  
Sample271    0    0    0  

[271 rows x 3303 columns]

In [15]:
#turning lefts and rights into 0s and 1s
for i in range(len(dataset)):
    if dataset[0][i] == 'left':
        dataset[0][i] = 0
    elif dataset[0][i] == 'right':
        dataset[0][i] = 1
    

In [16]:
import numpy as np
X = np.array(dataset.drop(0, axis=1),dtype=float)


In [17]:
y = np.array(dataset[0], dtype=float)


In [18]:
import sys
!{sys.executable} -m pip install xgboost
import xgboost as xgb

In [19]:
data_dmatrix = xgb.DMatrix(data=X, label=y)

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=123)

In [21]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [22]:
xg_reg.fit(X_train,y_train)

[02:56:30] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.3,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.1, max_bin=256,
             max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
             max_depth=5, max_leaves=0, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:linear', ...)

In [23]:
preds = xg_reg.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, preds)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [25]:
y_test

array([0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 1.])

In [26]:
preds

array([0.41278094, 0.5607083 , 0.51596165, 0.4742131 , 0.51559347,
       0.5369809 , 0.51307184, 0.52556103, 0.562222  , 0.40997586,
       0.47722563, 0.58590776, 0.41551065, 0.47744918, 0.50838375,
       0.38052833, 0.554187  , 0.551022  , 0.50575566, 0.54595757,
       0.3773533 , 0.37324077, 0.5113277 , 0.56341505, 0.5108932 ,
       0.49288264, 0.44711417, 0.40736437, 0.4812662 , 0.5589414 ,
       0.5061412 , 0.5850895 , 0.59739715, 0.5449014 , 0.49370885,
       0.3438956 , 0.42404512, 0.42384633, 0.48494834, 0.36592615,
       0.48472157, 0.50506026, 0.489868  , 0.42990705, 0.5129468 ,
       0.53957313, 0.4719524 , 0.49362013, 0.49737194, 0.37835073,
       0.44108474, 0.39125806, 0.40997586, 0.5306556 , 0.3447516 ,
       0.38083202, 0.4280553 , 0.49433765, 0.53550243, 0.5626729 ,
       0.45991772, 0.46480948, 0.47983837, 0.5739495 , 0.5293814 ,
       0.50138277, 0.44803274, 0.6223218 , 0.54839647, 0.44463345,
       0.47091144, 0.52730304, 0.49328917, 0.50838375, 0.50709

In [27]:
from sklearn.ensemble import AdaBoostClassifier
ada_boost = AdaBoostClassifier(n_estimators=95, learning_rate=0.8, random_state=42)
model = ada_boost.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [28]:
y_pred

array([0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0.])

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[31,  9],
       [23, 27]])

In [30]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.6444444444444445